name: Deploy to GCE
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd downloads/docker-cicd
          git pull origin main
          docker stop prjku
          docker rm prjku
          docker build -t prj12
          docker run --name prjku -d -p 8000:8000 prj12
